# -*- coding: utf-8 -*-
"""loan_qualifier

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QOguiN2_U-B817AaqXjMP7xqhT26yXx3
"""

#CS 175
#Maggie Volker

#loan_qualifier

#set salary
salary = float(input("Enter your annual salary: "))

if salary >= 30000:
  #set years on job
  years_on_job = float(input("How many years have you been on your job: "))
  if years_on_job >= 2:
    print("You qualify for the loan.")
  else:
    print("You must have been on your current job for at least two years to qualify.")
else:
  print("You must earn at least $30,000 per year to qualify.")